language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-baseops' ]; then cd .. && eval "mv $currentfolder generator-baseops" && cd generator-baseops; fi

