---
- name: install psycopg2
  apt: pkg=python-psycopg2 state=latest

- name: install postgresql
  apt:  pkg=postgresql state=latest

- name: overwrite postgresql.conf
  template: src=postgresql.conf.j2 dest=/etc/postgresql/9.1/main/postgresql.conf
  notify:
    - reload postgresql

- name: overwrite pg_hba.conf
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/9.1/main/pg_hba.conf
  notify:
    - reload postgresql

- name: start postgresql
  service: name=postgresql state=restarted

- name: create {{ rdbms_name }} database
  postgresql_db: name={{ rdbms_name }} state=present

- name: add {{ rdbms_name }} database user
  postgresql_user: db={{ rdbms_name }} name={{ rdbms_user }} password={{ rdbms_pass }} state=present
